### ISSUE TITLE
Garage door opener not working

### ISSUE THREAD

**Issue by tclarke1013** [tclarke1013/HomeAssistantConfig#5]
For some reason myq chamberlain stopped working.

Error message:
Mon May 21 2018 06:11:19 GMT-0400 (EDT)

Update for cover.garage_door_opener fails
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 204, in async_update_ha_state
    yield from self.async_device_update()
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 327, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/cover/myq.py", line 97, in update
    self._status = self.myq.get_status(self.device_id)
  File "/usr/lib/python3.6/site-packages/pymyq/__init__.py", line 153, in get_status
    devices = self.get_devices()
  File "/usr/lib/python3.6/site-packages/pymyq/__init__.py", line 124, in get_devices
    devices = devices.json()['Devices']
KeyError: 'Devices'

**Comment by tclarke1013** [comment]
Myq garage opener working again. Not sure of the reason.

**Comment by tclarke1013** [comment]
Stop working again. 

Update for cover.garage_door_opener fails
7:36 AM components/cover/myq.py (ERROR)
